export const environment = {
  production: false,
  cognitoUserPoolRegion: 'ap-southeast-1',
  cognitoUserPoolId: 'ap-southeast-1_frVXsIbgy',
  cognitoAppClientId: '1p151hon35tm0t4eco2cpt5fm6',
  cognitoIdentityPoolRegion: 'ap-southeast-1',
  cognitoIdentityPoolId: 'ap-southeast-1:446c226a-ce7d-4c7f-8f24-4ff90e4c6d12',
  oauthDomain: 'auth-ap-southeast-1.energie.co.id',
  oauthRedirectSignIn: 'http://localhost:4200',
  oauthRedirectSignOut: 'http://localhost:4200/sign-out',
  appTitle: 'HEI Solar',
  userApiName: 'userapi',
  userApiUrl: 'https://kqp0vnz6l7.execute-api.ap-southeast-1.amazonaws.com',
  lookupApiName: 'lookupapi',
  lookupApiUrl: 'https://krum0vt29f.execute-api.ap-southeast-1.amazonaws.com',
  stationApiName: 'assignapi',
  stationApiUrl: 'https://e24ydqvot9.execute-api.ap-southeast-1.amazonaws.com',
  defaultGridPageSize: 10,
  sesSourceEmailAddress: 'support@energie.co.id',
  allowSignUp: true
  };